services:
  postgresdb:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=default
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
